services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: helphive
      MYSQL_USER: helphive
      MYSQL_PASSWORD: helphive_pwd
      MYSQL_ROOT_PASSWORD: root_pwd
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot_pwd --silent"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      # >>> add these to satisfy application.properties <<<
      DB_HOST: mysql          # service name, not localhost
      DB_PORT: 3306
      DB_USERNAME: helphive   # must match MYSQL_USER in mysql service
      DB_PASSWORD: helphive_pwd
      # email (optional, reuse your .env values if you want)
      EMAIL: ${EMAIL}
      GMAIL_PASSWORD: ${GMAIL_PASSWORD}
    ports:
      - "8080:8080"


volumes:
  mysql_data:
